version: '3.9'

services:
  db:
    image: postgres:15.1-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: council
      POSTGRES_PASSWORD: council
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./initdb.d:/docker-entrypoint-initdb.d:ro
      - db:/var/lib/postgresql/data:rw

volumes:
  db:
